# Generated by Django 3.0.6 on 2020-05-31 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_zombodb.indexes
import django_zombodb.operations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archive', '0001_initial'),
    ]

    operations = [
        django_zombodb.operations.ZomboDBExtension(),
        migrations.CreateModel(
            name='ArchiveZombo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archives_zombo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='archivezombo',
            index=django_zombodb.indexes.ZomboDBIndex(fields=['content'], name='archive_arc_content_c15931_zombodb'),
        ),
    ]
