version: '3'
    
services:
  db:
    build:
      context: ./
      dockerfile: zombodb_Dockerfile
    environment:
      - POSTGRES_DB=archive
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.9
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  web:
    build: .
    command: >
      /bin/bash -c "
        sleep 15;
        python manage.py runserver 0.0.0.0:8000;
      "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - es